# Default Jekyll variables
title: Максим @Llorephie Мартьянов
author: Максим @Llorephie Мартьянов
email: web@llorephie.me
lang: ru-RU
description: Мысли одного девопса-распиздяя.
url: "https://llorephie.me"
twitter_username: llorephie
github_username:  llorephie

# Build settings
markdown: kramdown
theme: jekyll-bootstrap
remote_theme: llorephie/jekyll-bootstrap
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

sass:
    style: compressed
